### ISSUE TITLE
unresolved dependency: org.databrary#play-logback-access_2.10;0.2: not found

### ISSUE THREAD

**Issue by Apophenian** [cardamo/play-logback-access#1]
Hi there,

Do I need to enter a resolver url for this library, or am I just using the wrong version of play framework?  I'm currently using 2.2.3.

Many thanks in advance.

**Comment by dylex** [comment]
We've only published a scala 2.11 version currently (built on play 2.3).  We have previously used it on scala 2.10/play 2.2, though.  I may be able to rebuild and publish the 0.1 version this way, if you need it, or you can just change the play and scala versions in build.sbt and rebuild it yourself.

**Comment by dylex** [comment]
I've released a 0.1 build against scala 2.10.4/play 2.2.6.  Once it shows up you can give it a try.
