### ISSUE TITLE
Typo in the README.md

### ISSUE THREAD

**Issue by jeep87c** [cardamo/play-logback-access#11]
I think there's a typo in the README.md.

For 0.6, it says we should add in file `conf/application.conf`

`play.filters.enabled += org.databrary.PlayLogbackAccessFilter`

But I pretty sure it should be

`play.filters.enabled += org.databrary.PlayLogbackAccessModule`

**Comment by cardamo** [comment]
Hey @jeep87c,

nope, this line works as expected :) according to the new way of filters config: 
https://playframework.com/documentation/2.6.x/Migration26#appending-to-filters

PlayLogbackAccessModule is already included into play.**modules**.enabled in reference.conf

**Comment by jeep87c** [comment]
Awesome! Thanks for your reply.
