### ISSUE TITLE
Release version 0.6.0 for Scala 2.11.7

### ISSUE THREAD

**Issue by kasia-kittel** [cardamo/play-logback-access#12]
I can see you are prepared for cross compilation, but the release is missing in the repository (https://jcenter.bintray.com/org/databrary/play-logback-access_2.11/)

**Comment by knightpop** [comment]
👍

**Comment by cardamo** [comment]
Hey @kasia-kittel @knightpop 
Sorry for my late response.
I've found out that I can't publish to jcenter artifacts named `org.databrary:play-logback-access_2.11` because it was owned by previous publisher.

But it sould be available from my user repo: 
```
resolvers += Resolver.bintrayRepo("cardamo", "com.cardamo.play-logback-access")
```

**Comment by diversit** [comment]
Had same issue and found the same solution before finding this issue :-/
Please update the resolver documentation.

**Comment by cardamo** [comment]
@diversit done
