### ISSUE TITLE
#nullNA

### ISSUE THREAD

**Issue by doncorsean-private** [cardamo/play-logback-access#14]
Some logback-access operators are not working, any idea why this is?

\#asLong
\#nullNA

There is also a special operation that can be used with this AccessEvents:

\#nullNA{...} - if the pattern in curly braces evaluates to a dash ("-"), it will be replaced with a null value.

You may want to use it because many of the PatternLayout conversion specifiers from logback-access will evaluate to "-" for non-existent value (for example for a cookie, header or a request attribute).

So the following pattern...
```
<pattern>
  {
    "default_cookie": "%requestCookie{MISSING}",
    "filtered_cookie": "#nullNA{%requestCookie{MISSING}}"
  }
</pattern>
```
...will produce...
```
{
  "default_cookie": "-",
  "filtered_cookie": null
}
```
https://github.com/logstash/logstash-logback-encoder/blob/master/README.md#accessevent-patterns

**Comment by cardamo** [comment]
Hey @doncorsean !
I've tried the example from logstash docs and it works fine!

Here is how my encoder looks like:
```
  <encoder class="net.logstash.logback.encoder.AccessEventCompositeJsonEncoder">
      <providers>
          <pattern>
              <pattern>
                  {
                    "timestamp": "%date{ISO8601}",
                    "default_cookie": "%requestCookie{MISSING}",
                    "filtered_cookie": "#nullNA{%requestCookie{MISSING}}"
                  }
              </pattern>
          </pattern>
      </providers>
  </encoder>
```
And it gives messages like
```
{"timestamp":"2018-02-06 14:45:08,168","default_cookie":"-","filtered_cookie":null}
```
I've also noticed that if JSON is malformed it gives just, {}.

**Comment by doncorsean-private** [comment]
pebkac, ty for your prompt reply sir
