### ISSUE TITLE
Release versions 0.6.1 and 0.6.2 for Scala 2.11

### ISSUE THREAD

**Issue by mgladdish** [cardamo/play-logback-access#15]
As per #12, we're also missing versions 0.6.1 and 0.6.2 for Scala 2.11

**Comment by cardamo** [comment]
Hey @mgladdish 
Perhaps crossScalaVersions works not as I expected for publish.
I published 0.6.2 and 0.6.1 artifacts for scala 2.11 manually, please check if they get resolved now.
