### ISSUE TITLE
Play 2.7 support

### ISSUE THREAD

**Issue by vidma** [cardamo/play-logback-access#17]
is it planned to be released for play 2.7 (scala 2.11/2.12) ?

**Comment by cardamo** [comment]
Hey @vidma ,
I've checked that 0.6.2 version works nicely with play 2.7. Do you experience any problems with it?

The only problem I found is that scalatestplus-play dependency (test scope) should be upgraded, but it only affects this project at compile time, distribution is fine.

**Comment by vidma** [comment]
we'll see. for me, compilation was fine, didn't check logback logs yet.

however, possibly it would be cleaner to compile it against the actual play version.
