### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by mgladdish** [cardamo/play-logback-access#18]
Using later versions of Play means we can also use later versions of Scala.

Unless I'm missing something and later versions of Play no longer benefit from using this filter?

**Comment by cardamo** [comment]
@mgladdish 

I'm not aware about similar functionality being embedded into the framework itself, so perhaps it makes sense to upgrade to support scala 2.13/play 2.8

I just need some time to figure out another distribution service since jcenter is shutting down

**Comment by cardamo** [comment]
@mgladdish check out 0.7.0 release, please note that it's published to JitPack
