### ISSUE TITLE
Play 2.4 support

### ISSUE THREAD

**Issue by jamespamplin** [cardamo/play-logback-access#2]
This plugin seems to be incompatible with Play 2.4. A few of the issues I noticed were:
- Play throws Runtime exceptions when trying to load the plugin via: `play.api.Play.current.plugin[org.databrary.LogbackAccessPlugin]`

```
play.api.UnexpectedException: Unexpected exception[ConfigurationException: Guice configuration errors:

 1) Could not find a suitable constructor in org.databrary.LogbackAccessPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at org.databrary.LogbackAccessPlugin.class(plugin.scala:71)
   while locating org.databrary.LogbackAccessPlugin
```
- Plugins are now deprecated, although the API still works, see: https://www.playframework.com/documentation/2.4.x/ScalaPlugins
- `play.api.mvc.Headers` has changed from a trait (interface) to a class. Causes the following runtime error:

```
java.lang.IncompatibleClassChangeError: Found class play.api.mvc.Headers, but interface was expected
    at org.databrary.logback.PlayAccessEvent.getRequestHeader(adapter.scala:48)
```

I tried to create an adapter to get around these issues, but the last one has blocked me, as it requires the library source to be compiled against the updated interfaces in Play.

Any chance for Play 2.4 support?

**Comment by dylex** [comment]
Unfortunately we're no longer using play so I don't have any play 2.4 application to work on this with. I think the first problem might be fixed by my commit on the play-2.4 branch, but I haven't tested it and I'm not sure about the second issue yet. If you want to try it out we can try to iterate, or of course we'd accept a PR.
