### ISSUE TITLE
Release 0.8.0 not published well (pom not found)

### ISSUE THREAD

**Issue by sdudzin** [cardamo/play-logback-access#20]
Release 0.8.0 got published to Jitpack, however the pom file is not published it seems (the jar file is there).

The following url lists all the artefacts: https://jitpack.io/com/github/cardamo/play-logback-access/0.8.0/

```build.log
play-logback-access-0.8.0-javadoc.jar
play-logback-access-0.8.0-javadoc.jar.md5
play-logback-access-0.8.0-javadoc.jar.sha1
play-logback-access-0.8.0-sources.jar
play-logback-access-0.8.0-sources.jar.md5
play-logback-access-0.8.0-sources.jar.sha1
play-logback-access-0.8.0.jar
play-logback-access-0.8.0.jar.md5
play-logback-access-0.8.0.jar.sha1
play-logback-access-0.8.0.pom
play-logback-access-0.8.0.pom.md5
play-logback-access-0.8.0.pom.sha1
```

However the pom file is not downloadable which makes this version not usable (sbt can't download the dependency): https://jitpack.io/com/github/cardamo/play-logback-access/0.8.0/play-logback-access-0.8.0.pom

**Comment by sdudzin** [comment]
@cardamo any chance you can have a look?

**Comment by cardamo** [comment]
Yes, I will look into it soon :)

**Comment by cardamo** [comment]
Looks like it was a glitch on the jitpack side. One of many requests to https://jitpack.io/com/github/cardamo/play-logback-access/0.8.0/ was showing the full list of file (lucky load-balancing?). I removed the version to trigger a rebuild and seems like it helped
