### ISSUE TITLE
Add application.home property to the Context implemented by PlayLogbackAccessApiImpl

### ISSUE THREAD

**Issue by sashagavrilov** [cardamo/play-logback-access#4]
See https://github.com/playframework/playframework/blob/master/framework/src/play-logback/src/main/scala/play.api.libs.logback/LogbackLoggerConfigurator.scala#L30 for reference. 

It could be helpful to get access to this property from inside the config files.

**Comment by dylex** [comment]
I'd happily accept a PR for this, but as we're no longer using play I may not be able to provide anything myself.

**Comment by cardamo** [comment]
Hey @ilucker,
we can easily put any properties to the logging context with Guice module like this:
```
public class LogConfigModule extends AbstractModule {

    @Override
    protected void configure() {
        bind(AccessLogContextInitializer.class).asEagerSingleton();
    }

    public static class AccessLogContextInitializer {
        @Inject
        public AccessLogContextInitializer(PlayLogbackAccessApi accessApi) {
            // Get properties somehow. For example, from application config.
            Map<String, String> contextProps = ...;
            PlayLogbackAccess accessCtx = accessApi.context();
            contextProps.forEach(accessCtx::putProperty);
        }
    }
}
```
There is a problem with the layout used by default. [PatternLayout](https://github.com/qos-ch/logback/blob/master/logback-access/src/main/java/ch/qos/logback/access/PatternLayout.java) from the logback-access package doesn't render context values (unlike PatternLayout from logback-classic package). 
They have a [feature request](https://jira.qos.ch/browse/LOGBACK-1016) but it hasn't been implemented yet. But there are some other layouts that work fine, for example LogstashAccessLayout for logstash. It includes all the context into json messages.
