### ISSUE TITLE
Will never log anything in Play 2.5

### ISSUE THREAD

**Issue by matmannion** [cardamo/play-logback-access#6]
`PlayLogbackAcccessApiImpl` includes the line:

```
override def log(requestTime: Long, request: RequestHeader, result: Result, user: Option[String]): Unit =
  context.log _
```

The intention is to call `context.log` with the same arguments that have been passed to `api.log`, but in reality that doesn't happen because the arguments are swallowed by the method itself.

Compare results in the SBT console:

```
scala> def log(requestTime: Long = -1, request: String, result: String, user: Option[String] = None): String = {
     |  "Logged"
     |}
log: (requestTime: Long, request: String, result: String, user: Option[String])String

scala> def log2(requestTime: Long, request: String, result: String, user: Option[String]) =
     |   log _
log2: (requestTime: Long, request: String, result: String, user: Option[String])(Long, String, String, Option[String]) => String

scala> log(request = "GET /", result = "200 OK")
res0: String = Logged

scala> log2(-1, "GET /", "200 OK", None)
res1: (Long, String, String, Option[String]) => String = <function4>
```

Note the return type of `log2` here, and the result when it's called - nothing actually happens. I think what was intended was to just pass all arguments through:

```
scala> def log3 = log _
log3: (Long, String, String, Option[String]) => String

scala> log3(-1, "GET /", "200 OK", None)
res2: String = Logged
```

To enable `PlayLogbackAccessApiImpl` to continue to implement `PlayLogbackAccessApi.log`, it's probably best to just pass arguments through directly to the method instead of using `_`.

**Comment by ctoomey** [comment]
Hi @dylex, will you please make this fix available on maven central? The latest 0.5 version there doesn't have it.

**Comment by dylex** [comment]
@ctoomey 0.5.1 is now published.

**Comment by ctoomey** [comment]
Thx @dylex
