### ISSUE TITLE
Build for play 2.6 and scala 2.12

### ISSUE THREAD

**Issue by cardamo** [cardamo/play-logback-access#8]
Hey @dylex, thanks for this lib!

[Play 2.6 is coming](https://github.com/playframework/playframework/releases/tag/2.6.0-M2), could you publish a build with scala 2.12?

**Comment by dylex** [comment]
Sorry for the slow response.  Unfortunately, I'm no longer involved with this organization, but hopefully @makslevental can help.

**Comment by cardamo** [comment]
Fixed.
Thanks @makslevental for transfering the repository
