### ISSUE TITLE
Runtime failures under play 2.5.14

### ISSUE THREAD

**Issue by abiacco** [cardamo/play-logback-access#9]
Server fails to start due to 2.5.14 updating logback classic/core jars to 1.2.3.
Failure due to suspected incompatible logback-access version used in play-logback-access.
Reference [https://jira.qos.ch/browse/LOGBACK-1269](url)

Error is:
```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: ch.qos.logback.core.util.ContextUtil.addHostNameAsProperty()V
  at org.databrary.PlayLogbackAccessApiImpl.<init>(module.scala:47)
  while locating org.databrary.PlayLogbackAccessApiImpl
```

Libs:
./ch.qos.logback.logback-access-1.1.4.jar
./ch.qos.logback.logback-core-1.2.3.jar
./ch.qos.logback.logback-classic-1.2.3.jar
./org.databrary.play-logback-access_2.11-0.5.1.jar
./com.typesafe.play.play-logback_2.11-2.5.14.jar

Workaround:
Add to build.sbt:
`libraryDependencies += "ch.qos.logback" % "logback-access" % "1.2.3"`

**Comment by cardamo** [comment]
Fixed.

Binaries are currently available on this repository
```resolvers += Resolver.bintrayRepo("cardamo", "com.cardamo.play-logback-access")```
This repo is already linked to jcenter but the latest builds aren't available on it yet. Probably it will take some time for repositories to sync.
